= Data Management : All Notes !
:TOC:

== Types of Information

- Logs
- Media (Images, music, videos)
- Software
-- code
-- config
-- data
- Templates
- Educational Info
-- Guides & Manuals
-- Infographics

== Data Storage Locations
- Git platforms (github, gitlab, etc..)
- 
- Chat Platforms (Slack, Temas, Discord, etc ...)
- Email
- Local Storage Devices (HDD, SSD, NAS, Mobile, etc ...)
- Cloud File Storage (Google Drive, OneDrive, DropBox, etc )
- Cloud Data Management & Storage ( Google Sheets, Google Docs, Excel Online, AirTable, etc ...)

== Storage Device Breakdown

----
- business
- edu
- side-projects
- personal
- arhcives
- env
-- env_managmenet_tools
-- vms
-- data


----

== Files

----
timestamp_category_sub-category_short-desc_v.ext
category_sub-category_short-desc_v.ext
project-name_category_sub-category_short-desc_v.ext
----

== Folders

.Business
----
- AccountName (prefix own accounts with underscore)
-- dep_DepartmentName
-- br_BranchName

----

.Example
----  
ClientOrBrandNameWithinCompany
-- dep_IT
-- dep_Marketing
-- dep_Finance
-- dep_Legal
-- dep_HR
-- dep_CustomerService
-- dep_Production
-- dep_Operations
-- dep_RnD
-- dep_ProductDevelopment
-- br_SydneyOffice
-- br_SheppertonOffice



----

.EDU & Side Projects

----
- edu
-- industry
--- subject

- side-projects
-- industry
--- subject

- gaming
-- games
-- gaming-tools
-- other-apps

- art
-- Collection
-- Tools


- music
-- collection-by-language
--- EN
--- AR

--- playlists
--- tools
---- media-player

-- DJ
-- Composing

- photography
-- photos_raw
-- photos_processed

----

.Personal
----

- media
-- family-archive
-- movies

----


== Document Formats
- list
- guide
- manual
- tutorial
- case study
- changelog
- review
- artifact ?
- plan
- overview
- stats
- template
- infographic
- data visuals ?
- image
- report
- 
