= Guide to Programming with Python3
:TOC:
== Introduction
!!NOTE : Fix code samples for python3 !

Python is a general-purpose interpreted, interactive, object-oriented, and high-level programming language. It was created by Guido van Rossum during 1985- 1990. Like Perl, Python source code is also available under the GNU General Public License (GPL). This tutorial gives enough understanding on Python programming language.

== Installation & Setup
=== Install on Ubuntu
----
sudo apt install python3-venv python3-pip 
python3 -m pip install --user --upgrade pip

----
Other installation options listed on  https://packaging.python.org/guides/installing-using-linux-tools/#installing-pip-setuptools-wheel-with-linux-package-managers

=== Setup Virtual Environment with `virtualenv`
https://packaging.python.org/guides/installing-using-pip-and-virtualenv/
----
python3 -m pip install --user --upgrade virtualenv


python3 -m virtualenv env
source env/bin/activate
pip install PACKAGENAME

deactivate
---- 

=== Setup Virtual Environment with `venv`
----
sudo apt install python3-venv 

python3 -m venv /DIR

---- 
=== General syntax example 
[source,python]
----
#!/usr/bin/python

import sys

print("Hello, Python!")

#variables 
word = 'word'
sentence = "This is a sentence."
paragraph = """This is a paragraph. It is
made up of multiple lines and sentences."""
counter = 100          # An integer assignment
miles   = 1000.0       # A floating point
name    = "John"       # A string
a,b,c = 1,2,"john" #Multiple assignments
days = ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday']

#Control Flow Tools

if expression : 
   suite
elif expression : 
   suite 
else : 
   suite
   
   
words = ['cat', 'window', 'defenestrate']
for w in words:
   print(w, len(w))
----

[source,python]
----
#!/usr/bin/python
import subprocess
subprocess.run(["ls", "-l"])
----

=== Strings 
[source,python]
----
#!/usr/bin/python
str = 'Hello World!'

print str          # Prints complete string
print str[0]       # Prints first character of the string
print str[2:5]     # Prints characters starting from 3rd to 5th
print str[2:]      # Prints string starting from 3rd character
print str * 2      # Prints string two times
print str + "TEST" # Prints concatenated string

----

=== Lists 
Lists are the most versatile of Python's compound data types. A list contains items separated by commas and enclosed within square brackets ([]). To some extent, lists are similar to arrays in C. One difference between them is that all the items belonging to a list can be of different data type.
[source,python]
----
#!/usr/bin/python

list = [ 'abcd', 786 , 2.23, 'john', 70.2 ]
list[5] = '5th item'
list.append('appended value')

tinylist = [123, 'john']

print list          # Prints complete list
print list[0]       # Prints first element of the list
print list[1:3]     # Prints elements starting from 2nd till 3rd 
print list[2:]      # Prints elements starting from 3rd element
print tinylist * 2  # Prints list two times
print list + tinylist # Prints concatenated lists

----

=== Tuples 
The main differences between lists and tuples are: Lists are enclosed in brackets ( [ ] ) and their elements and size can be changed, while tuples are enclosed in parentheses ( ( ) ) and cannot be updated. Tuples can be thought of as read-only lists.
[source,python]
----
#!/usr/bin/python

tuple = ( 'abcd', 786 , 2.23, 'john', 70.2  )
tinytuple = (123, 'john')

print tuple           # Prints complete list
print tuple[0]        # Prints first element of the list
print tuple[1:3]      # Prints elements starting from 2nd till 3rd 
print tuple[2:]       # Prints elements starting from 3rd element
print tinytuple * 2   # Prints list two times
print tuple + tinytuple # Prints concatenated lists

----

=== Dictionary 
Python's dictionaries are kind of hash table type. They work like associative arrays or hashes found in Perl and consist of key-value pairs. A dictionary key can be almost any Python type, but are usually numbers or strings. Values, on the other hand, can be any arbitrary Python object. Dictionaries are enclosed by curly braces ({ }) and values can be assigned and accessed using square braces ([]).
[source,python]
----
#!/usr/bin/python

dict = {}
dict['one'] = "This is one"
dict[2]     = "This is two"

tinydict = {'name': 'john','code':6734, 'dept': 'sales'}


print dict['one']       # Prints value for 'one' key
print dict[2]           # Prints value for 2 key
print tinydict          # Prints complete dictionary
print tinydict.keys()   # Prints all the keys
print tinydict.values() # Prints all the values

----

=== Operators https://www.tutorialspoint.com/python/python_basic_operators.htm[+]

==== Arithmetic Operators 
|===
|Operator |Description |Example
|+ | | a + b = 12
|- | | a - b = 6
|* | | a * b = 27
| / | | a / b = 3
| % | Modulus| a % b = 0
| ** | Exponent | a ** b = 729
| // | Floor Division | 9//2 = 4 and 9.0//2.0 = 4.0, -11//3 = -4, -11.0//3 = -4.0

|===
==== Comparison Operators  
ToDo


=== Functions

[source,python]
----
#!/usr/bin/python

# Function definition is here
def printme( str ):
   "This prints a passed string into this function"
   print str
   return;

# Now you can call printme function
printme("I'm first call to user defined function!")
printme("Again second call to the same function")
----

== Using Python Packapge Manager PIP
`curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py`

[Source,python]
----

----


== Useful Links
- https://www.tutorialspoint.com/python
- Python 3 – Quick Reference Card:   http://www.cs.put.poznan.pl/csobaniec/software/python/py-qrc.html
- docs.python.org/3: https://docs.python.org/3/contents.html
- Python Full Stack https://www.fullstackpython.com/


== Credits
- https://www.fullstackpython.com/
- https://www.tutorialspoint.com/python
- 
