= General Naming Convention
How should varialbes, functions, classes and namespaces should be named ?

== Other notes
- https://stackoverflow.com/questions/421965/anyone-else-find-naming-classes-and-methods-one-of-the-most-difficult-parts-in-p 
- context + verb + how
- verbAdjectiveNounStructure 
- 
- Transformer:  XFromY / XToY
- 

== useful-naming-conventions

.From https://caseysoftware.com/blog/useful-naming-conventions

"
verbAdjectiveNounStructure – with Structure and Adjective as optional parts

For verbs, I stick to action verbs: save, delete, notify, update, or generate.  Once in a while, I use "process" but only to specifically refer to queues or work backlogs.

For nouns, I use the class or object being interacted with.  In web2project, this is often Tasks or Projects.  If it's Javascript interacting with the page, it might be body or table.  The point is that the code clearly describes the object it's interacting with.

The structure is optional because it's unique to the situation.  A listing screen might request a List or an Array.  One of the core functions used in the Project List for web2project is simply getProjectList.  It doesn't modify the underlying data, just the representation of the data.

The adjectives are something else entirely.  They are used as modifiers to the noun.  Something as simple as getOpenProjects might be easily implemented with a getProjects and a switch parameter, but this tends to generate methods which require quite a bit of understanding of the underlying data and/or structure of the object… not necessarily something you want to encourage. By having more explicit and specific functions, you can completely wrap and hide the implementation from the code using it. Isn't that one of the points of OO?
"

----


== Namin convention based on Laravel
https://laravel.com/api/9.x/

=== Namespaces and Class Names 
- Auth
** Access
- Cache
- Broadcasting: used with WebSockets for live updates ?
- Bus ?
- Config
- Console
- Container
- Cookie
- Database
- Encryption
- Events
- Filesystem
- Mail
- Http: HTTP Client

- Notificaitons
- Queue
- Routing
- Session
- Support ?
- Validation 
- View
- 

=== Class Name Keywords
- Factory
- Adabter
- Decorator
- Strategy
- Facade
- View
- Response
- Parser
- Provider

- Validator 
- 
