= Ubuntu : Network Shared Folder.
The purpose of this document is to showcase methods of sharing & possibly mounting folders across networks.


== Using FTP:

- install `sudo apt install curlftpfs`
- create mountpoint folder `sudo mkdir /mnt/ftpmount` 
- mout the ftp folder using `sudo curlftpfs -o allow_other UserName:PASS@domain.com /mnt/ftpmount`
** the `-o allow_other` allows non-root users to access a folder mounted by root.


== Using WebDav

- install webdav client `sudo apt install davfs2`
- On debian based disretos, run the followingcommand to allow non-root users to mount webdav folders `sudo dpkg-reconfigure davfs2`
- sudo mount -t davfs -0 uid=user,gui=users,mod=775 http://DOMAIN/webdav /mnt/FOLDER


== Using NFS

=== NFS Server
- install NFS server `sudo apt-get install nfs-kernel-server`
- update `/etc/exports` to include the following:
----
/shared/folders/parent 192.168.0.0/24(rw,fsid=0,insecure,no_subtree_check,async)
/shared/folders/parent/child 192.168.0.0/24(rw,nohide,insecure,no_subtree_check,async)
----

- restart nfs : `service nfs restart`

==== Useful NFS Server Commands
`service nfs reload`



=== NFS Client

Sample code for mounting NFS folder:
`sudo mount -t nfs4 -o proto=tcp,port=2049 192.168.0.112:/ /home/michael/_mh-pc2_media`

=== Samba

https://help.ubuntu.com/community/How%20to%20Create%20a%20Network%20Share%20Via%20Samba%20Via%20CLI%20%28Command-line%20interface/Linux%20Terminal%29%20-%20Uncomplicated,%20Simple%20and%20Brief%20Way!

----
sudo apt-get install samba

sudo smbpasswd -a <user_name>

# Edit smb.conf then add the config below
sudo vi /etc/samba/smb.conf
[<folder_name>]
path = /home/<user_name>/<folder_name>
valid users = <user_name>
read only = no

# Restart the service
sudo service smbd restart



----



