= October CMS Guide

== About October CMS

== Installation & Config Guide

=== Initial Setup
```
composer create-project october/october myoctober
cd ./myoctober
php artisan october:install
```
To access the backend, add `/backend` to your root domain (unless you changed the default backend tour during installation).

=== Setting up the scheduler
For scheduled tasks to operate correctly, you should add the following Cron entry to your server. Editing the crontab is commonly performed with the command `crontab -e`.
`* * * * * php /path/to/artisan schedule:run >> /dev/null 2>&1`

=== Understanding The Basics

==== Active Theme
The active theme is set with the activeTheme parameter in the config/cms.php file or with the Theme Selector on the System > CMS > Front-end Theme back-end page. The theme set with the Theme Selector overrides the value in the config/cms.php file.


== File Structure
October supports a single level subdirectories for pages, partials, layouts and content files (the assets directory can have any structure).

```
themes/
    website/          <=== Theme starts here
        pages/            <=== Pages directory
            home.htm
                blog/                  <=== Subdirectory
                    archive.htm
                    category.htm
        layouts/          <=== Layouts directory
            default.htm
        partials/          <=== Partials directory
            sidebar.htm
        content/          <=== Content directory
            intro.htm
        assets/            <=== Assets directory
            css/
                my-styles.css
            js/
                images/
```


== Templates Hierarchy

[plantuml]
----


----

== Plugins


=== How to create templates?
pages, partials and layout templates can include up to 3 sections: configuration,
PHP code, and Twig markup. Sections are separated with the `==` sequence. For example:
Notes:
* The config section uses .INI format with string values enclosed in quotes.
* The PHP section can have optional opening & closing tags. Also. only functions & name spaces are allowed.

----
url = "/blog"
layout = "default"
==
function onStart()
{
    $this['posts'] = ...;
}
==
<h3>Blog archive</h3>
{% for post in posts %}
    <h4>{{ post.title }}</h4>
    {{ post.content }}
{% endfor %}
----


for more information, visit https://octobercms.com/docs/cms/themes

== Theme Development
- Theme development docs: https://octobercms.com/docs/themes/development

== Page execution life cycle handlers

. Layout onInit() function.
. Page onInit() function.
. Layout onStart() function.
. Layout components onRun() method.
. Layout onBeforePageStart() function.
. Page onStart() function.
. Page components onRun() method.
. Page onEnd() function.
. Layout onEnd() function.

== Internals

=== Routing

==== Parser
https://octobercms.com/docs/services/parser
== Problems & Solutions:

=== .htaccess & 403 error on bitnami server :
`Options +FollowSymLinks` apache options must be added to the .htaccess file.


== Useful Links
https://octobercms.com/docs
