= Bitnami Web Server Usage Guide

== Running Bitnami Server From Command Line

. Control Script: start, restart & stop the services.
```
./ctlscript.sh ( start | restart | stop )

```

. loads environment variables that need to be present when using many of the
command line tools included in the stack, such as mysql, php or openssl.
```
./use_lampstack
```

== Adding Custom Application to Bitnami Server

=== Step 1 :
in `installdir/apps/myapp/conf/` create the following files :

- `httpd-app-config`
```
<Directory "installdir/apps/myapp/htdocs">
    Options +MultiViews
    AllowOverride None
    <IfVersion < 2.3 >
    Order allow,deny
    Allow from all
    </IfVersion>
    <IfVersion >= 2.3>
    Require all granted
    </IfVersion>
</Directory>

Include installdir/apps/myapp/conf/htaccess.conf
```

- `httpd-prefix.conf`
```
Alias /myapp/ "installdir/apps/myapp/htdocs/"
Alias /myapp "installdir/apps/myapp/htdocs"

Include "installdir/apps/myapp/conf/httpd-app.conf"
```

- `httpd-vhosts.conf` _seems to be unsed on localhost! Will need a proper server setup?_
```
<VirtualHost *:8080>
  ServerName myapp.example.com
  DocumentRoot "installdir/apps/myapp/htdocs"
  Include "installdir/apps/myapp/conf/httpd-app.conf"
</VirtualHost>

<VirtualHost *:8444>
  ServerName myapp.example.com
  DocumentRoot "installdir/apps/myapp/htdocs"
  SSLEngine on
  SSLCertificateFile "installdir/apps/myapp/conf/certs/server.crt"
  SSLCertificateKeyFile "installdir/apps/myapp/conf/certs/server.key"
  Include "installdir/apps/myapp/conf/httpd-app.conf"
</VirtualHost>
```

=== Step 2 :

- To access the app using a domain-prefix, add the following to `installdir/apache2/conf/bitnami/bitnami-apps-prefix.conf`
```
Include "installdir/apps/myapp/conf/httpd-prefix.conf"
```
this will make the app available at DomainName:PORT/AppName

- *or* to enable vhosts, add the following to `installdir/apache2/conf/bitnami/bitnami-apps-vhosts.conf `
```
Include "installdir/apps/myapp/conf/httpd-vhosts.conf"
```

== Disable PHP Caching on Bitnami Server

- Comment out the following lines in `installdir/installdir`
```
Include conf/pagespeed.conf
Include conf/pagespeed_libraries.conf
```

- Comment out the following lines (or set to 0) in `installdir/php/etc/php.ini`
```
opcache.enable=1
opcache.enable_cli=1
```

- MUST restart the server using `./ctlscript.sh` to restart PHP to apply the changes.

== Mutiple App Instancessudo ./bitnami-wordpress-VERSION-module-linux-x64-installer.run --wordpress_instance_name
.Wordpress
```
sudo ./bitnami-wordpress-VERSION-module-linux-x64-installer.run --wordpress_instance_name NEW_BLOG_NAME
```
https://docs.bitnami.com/installer/apps/wordpress/configuration/install-several-wordpress-modules/
