= Wordpress Developer Guide

== What is Wordpress (AKA WP)
WordPress (WordPress.org) is a content management system (CMS) written in PHP ...  https://en.wikipedia.org/wiki/WordPress[Source : Wikipidia]



== Useful Links
=== General Information
- https://wordpress.org/[Project website : Wordpress.org] 
- https://wordpress.org/support/[Wordpress Documentation]
- https://developer.wordpress.org/[WordPress Developer Documentation]
- https://www.codeinwp.com/blog/best-free-wordpress-themes/ 
- https://www.freshdesignweb.com/free-bootstrap-wordpress-themes/
- https://premium.wpmudev.org/blog/essential-wordpress-plugins/?utm_expid=3606929-105.kKHVTz43T_CV513Vo9oSow.0&utm_referrer=https%3A%2F%2Fwww.google.com.au%2F

- Michael habib's Favorited items on wordpress.org : https://profiles.wordpress.org/michaelhabib16#content-favorites

=== Repos of Plugins & Frameworks (Not listed on WordPress marketplace)
- https://github.com/jessuppi
- http://wppb.io/
- Sage / roots


== Recomended Plugins

=== TEMP


ManageWP - Worker: by ManageWP 
Akismet Anti-Spam: by Automattic
All 404 Redirect to Homepage: by Fakhri Alsadi
Demo Sticky Bar: by B3multimedia
Bloom: by Elegant Themes
Contact Form 7: by Takayuki Miyoshi
Divi 100 Article Cards: by Elegant Themes
Divi 100 Hamburger Menu: by Elegant Themes
Divi 100 Login Page: by Elegant Themes
Divi Switch: by divi.space
Woo Layout Injector: by Sean Barton - Tortoise IT
Easy Theme and Plugin Upgrades: by Chris Jean
Elegant Themes Support: by Elegant Themes
Elegant Themes Updater: by Elegant Themes
Facebook for WooCommerce: by Facebook
Groups WooCommerce: by itthinx
Groups: by itthinx
Heartbeat Control: by Jeff Matson
Monarch Plugin: by Elegant Themes
Really Simple CAPTCHA: by Takayuki Miyoshi
WooCommerce Customer/Order CSV Export: by SkyVerge
WooCommerce PayPal Powered by Braintree Gateway: by WooCommerce
WooCommerce Order Status Control: by SkyVerge
WooCommerce USPS Shipping: by WooCommerce
WooCommerce Subscriptions: by Prospress Inc
WooCommerce: by Automattic 
WordPress HTTPS: by Mike Ems 
Yoast SEO: by Team Yoast 



=== Security

=== Backup & Maintenance

=== SEO

=== Social Media Integration


=== Authentication & User Mangement

=== Visual Website Builders

=== Enhancements & Additional Features 
- Sidebar manager


== Recomended Themes
=== Sage Theme Framework
- Sage is a WordPress starter theme with a modern development workflow.
- https://github.com/roots/sage
- Sass for stylesheets
- Modern JavaScript
- Webpack for compiling assets, optimizing images, and concatenating and minifying files
- Browsersync for synchronized browser testing
- Blade as a templating engine
- Controller for passing data to Blade templates
- CSS framework (optional): Bootstrap 4, Bulma, Foundation, Tachyons, Tailwind


=== SiteOrigin Vantage (Free)
- Works well with SiteOrigin Page Builder

=== UnderStrap: Underscores starter theme + Bootstrap 4 (Free)
- Has a sample child theme to get started quickly.
- Aimed at developers and does not include pretty css for production sites.


=== Sparkling

- Free theme with all color & layout options included.


=== Divi (Paid) 
- Provided by Elegant Themes. 

=== Avada (Paid) 
- Priced at $60 with over 300,000 sales. (ToDo) Test & Provide more info.

=== Components.underscores.me theme generator by WP

=== Customizr (non-bootstrap) 

=== WordPress Themes & Plugins Marketplaces
==== https://themefuse.com (premium) 
- Pricing:
** $60 for single site
** $100 for all themes and unlimited sites.
** $250 life time access & updates.

==== Elegent Themes 
- Pricing:
** $70 for access to all themes and updates for a year.
** $90 Access to all themes & plugins with updates for one year
** $250 lifetime access & updates.
** Also checkout Elegant market Place: https://elegantmarketplace.com/

- Third Party Elegant Themes Software:
** http://www.divithemeexamples.com/divi-layouts/
** http://www.divithemeexamples.com/divi-showcase-category/free-divi-child-themes/
** https://elegantdivilayouts.com/
** http://divicreative.com
** https://divicake.com/
** https://besuperfly.com/shop/
** https://quiroz.co/divi-tutorials-much/divi-layout-kits/

== How to Install & Configure WP ?

=== Setting File permission
The recommedned file permissions are  `755` for folders & `644` for files. 

To correct WordPress file permission, you can run the following commands in the terminal at the root level of the project (Usually `public_html/`)
----
find . -type d -exec chmod 755 {} +
find . -type f -exec chmod 644 {} +
----


== How to Create a WP Plugin?


== How to Create a WP Theme ?
=== Useful Links
- https://codex.wordpress.org/Theme_Development 
- https://codex.wordpress.org/Site_Design_and_Layout 
- https://codex.wordpress.org/Child_Themes

== How to Create a WP Child Theme ?

== WordPress Coding Standards
I'll only cover the important points, the rest can be found on https://make.wordpress.org/core/handbook/best-practices/coding-standards/
=== PHP Coding Standards

.Naming Convention
[source,php]
----
class Class_Name {

   private $variable_name = ""
   const CONSTANT_NAME = ""
   
   public function function_name($some_variable){
      
   }
}
----



== Working with WP CLI (WordPress Command Line Interface)

=== WP CLI Commands
https://developer.wordpress.org/cli/commands/

.Download WP using WP CLI
----
wp core download
----

.Install recommended plugins using WP CLI
----
wp plugin install \
woocommerce \
cc-child-pages \
contact-form-7 \
easy-wp-smtp \
post-smtp \
simple-image-sizes \
imagemagick-engine \
w3-total-cache \
updraftplus \
all-in-one-wp-security-and-firewall \
user-role-editor \
duplicate-post \
wp-force-login \
query-monitor
----

.Generate pages using WP CLI
----
wp post create --post_type=page --post_status="publish" --post_title="Home"
wp post create --post_type=page --post_status="publish" --post_title="About"
wp post create --post_type=page --post_status="publish" --post_title="Contact"
wp post create --post_type=page --post_status="publish" --post_title="Services"
wp post create --post_type=page --post_status="publish" --post_title="Terms & Conditions"
wp post create --post_type=page --post_status="publish" --post_title="Privacy Policy"

----

.Create menus using WP CLI
----
wp menu create "Primary Menu"
wp menu location assign primary-menu primary
wp menu create "Secondary Menu"
wp menu create "Sidebar Menu"
wp menu create "Footer Menu"

----

== WP REST API
=== Links
- https://developer.wordpress.org/rest-api
- https://developer.wordpress.org/rest-api/reference/posts/
- Custom Routes: https://developer.wordpress.org/reference/functions/register_rest_route/

=== Code Samples
----
DominName/wp-json/wp/v2/posts?per_page=3&orderby=date&order=desc&status=publish
----

== Understanding WP Action & Filter Hooks 


=== Commonly used action hooks.
----
muplugins_loaded
plugin_loaded`
init
wp_loaded                          
wp
----

.Commonly used filter hooks.
----


----
 

=== Useful Links
https://adambrown.info/p/wp_hooks/hook
https://codex.wordpress.org/Plugin_API/Action_Reference
 

 

 

 
