
= How to Store Personal & Business Digital Data :
The goal of this research is to find an optimal way to store and organize personal & business data. The problem i'm having is creating a simple and meaningful file structure and naming convention for all the data i collect.

== Notes related to Personal Data
- projects/
** project-cat_project-name/

- resources/

- software


== Notes related to Business Data

=== File Structure

- accounts/
** account-name/
*** business-department/
**** product-category_product-name/

.Examples:
*** r-and-d/
**** project-category_project-name/

- resources/
** resource-category_resource-name/

- software/
** software-category_software-name/:

- shared-fs/ (for shared file system folders like google driver, dropbox or any other local or external network fs)


== Categorization Criteria : How to categories information ?


Document tags ?!
By Department: IT, Finance, Legal, HR, Marketing, Sales, Production, Operations, Customer Service, R&D
By Document Type :  Changelog, Contract, Tutorial (Detailed Instructions), Guide (Simple Instructions), Manual, Template, Form, Source Code, Plan, Intro / Description, Diagram.
By Intended User : Customer, User (System user)(Internal or External), Developer (Internal or External)
By Software Category : Website, CMS, Plugin, Add-on, Theme, Child Theme,
By Software name: Wordpress, FMS, ...
Usage examples
For a page with the title "How to access Wordpress & edit content guide", add tags → IT, Guide, User, Developer, Wordpress, CMS .




=== Document Types

== Useful Links
- https://www.convinceandconvert.com/content-marketing/content-to-fill-calendar/[ 105 Types of Content to Fill Up Your Editorial Calendar]
- https://contentmarketinginstitute.com/2016/04/fresh-content-formats[8 Ways to Take a Fresh Approach to Content Formats]


== other Notes

https://en.wikipedia.org/wiki/Organization
https://en.wiktionary.org/wiki/process
https://en.wikipedia.org/wiki/Function_model
https://en.wikipedia.org/wiki/Data
http://www.exadox.com/en/articles/file-naming-convention-ten-rules-best-practice
http://library.stanford.edu/research/data-management-services/data-best-practices/best-practices-file-naming


=== File Naming - Thought Processes:
* What(type), From Whom(Target), Why, When(DateStamp), Version (Version Control)
** Example(this document filename)
** process_for-admin_data-organization_v1_2017-6-28
* What’s involved ?
** people
** process
** technology
** content
* Types of Data  ?
** Tasks
** Binding Documents / Legal
** T & C
** Contracts
** Policies
** Docs
** Tutorials
** Guides
** Manuals
** Processes
** Research Notes ?
** Analysis ?
** Reports ?
** Entity:
*** Contact/ Person
*** Customers
*** Staff
*** Business / Organization
* Metadata
** Tags
** Categories
** Version
** Date / Time / DateTime
** Meta Description
** User(s) name
** Sub-Type / Type of info? Lookup correct terminology:
** Questions

